{"ArtistLink": "http://www.timba.com/tours/adalberto-alvarez-y-su-son"}
{"ArtistLink": "http://www.timba.com/tours/afro-cuban-all-stars"}
{"ArtistLink": "http://www.timba.com/tours/aisar-y-el-expresso-de-cuba"}
{"ArtistLink": "http://www.timba.com/tours/alain-daniel"}
{"ArtistLink": "http://www.timba.com/tours/alexander-acosta"}
{"ArtistLink": "http://www.timba.com/tours/anacaona"}
{"ArtistLink": "http://www.timba.com/tours/arlenys"}
{"ArtistLink": "http://www.timba.com/tours/arnaldo-y-su-talisman"}
{"ArtistLink": "http://www.timba.com/tours/azucar-negra"}
{"ArtistLink": "http://www.timba.com/tours/bamboleo"}
{"ArtistLink": "http://www.timba.com/tours/la-barriada"}
{"ArtistLink": "http://www.timba.com/tours/boni-kelly"}
{"ArtistLink": "http://www.timba.com/tours/buena-fe"}
{"ArtistLink": "http://www.timba.com/tours/buena-vista-social-club"}
{"ArtistLink": "http://www.timba.com/tours/calixto-oviedo-2"}
{"ArtistLink": "http://www.timba.com/tours/calixtos-way-quintet-tours"}
{"ArtistLink": "http://www.timba.com/tours/calle-real"}
{"ArtistLink": "http://www.timba.com/tours/caribe-girls"}
{"ArtistLink": "http://www.timba.com/tours/chacal"}
{"ArtistLink": "http://www.timba.com/tours/osvaldo-chacon"}
{"ArtistLink": "http://www.timba.com/tours/charanga-forever"}
{"ArtistLink": "http://www.timba.com/tours/charanga-habanera"}
{"ArtistLink": "http://www.timba.com/tours/charanga-havana-all-stars"}
{"ArtistLink": "http://www.timba.com/tours/conjunto-chappottin"}
{"ArtistLink": "http://www.timba.com/tours/conquistadores-de-la-salsa"}
{"ArtistLink": "http://www.timba.com/tours/contrabando"}
{"ArtistLink": "http://www.timba.com/tours/creol-choir-of-cuba"}
{"ArtistLink": "http://www.timba.com/tours/cubanismo"}
{"ArtistLink": "http://www.timba.com/tours/d-oviedo-lily"}
{"ArtistLink": "http://www.timba.com/tours/descemer-bueno"}
{"ArtistLink": "http://www.timba.com/tours/eddy-k"}
{"ArtistLink": "http://www.timba.com/tours/el-nino-y-la-verdad"}
{"ArtistLink": "http://www.timba.com/tours/eminencia-clasica"}
{"ArtistLink": "http://www.timba.com/tours/gente-d-zona"}
{"ArtistLink": "http://www.timba.com/tours/gilito"}
{"ArtistLink": "http://www.timba.com/tours/grupo-danson"}
{"ArtistLink": "http://www.timba.com/tours/haila"}
{"ArtistLink": "http://www.timba.com/tours/havana-d-primera"}
{"ArtistLink": "http://www.timba.com/tours/irakere"}
{"ArtistLink": "http://www.timba.com/tours/issac-delgado"}
{"ArtistLink": "http://www.timba.com/tours/jacob-forever"}
{"ArtistLink": "http://www.timba.com/tours/jose-pepito-gomez"}
{"ArtistLink": "http://www.timba.com/tours/jovenes-clasicos-del-son"}
{"ArtistLink": "http://www.timba.com/tours/klimax"}
{"ArtistLink": "http://www.timba.com/tours/laritza-bacallao"}
{"ArtistLink": "http://www.timba.com/tours/lopez-ernan"}
{"ArtistLink": "http://www.timba.com/tours/leoni-torres"}
{"ArtistLink": "http://www.timba.com/tours/lopez-nussa-harold"}
{"ArtistLink": "http://www.timba.com/tours/los-4"}
{"ArtistLink": "http://www.timba.com/tours/manolin"}
{"ArtistLink": "http://www.timba.com/tours/manolito-y-su-trabuco"}
{"ArtistLink": "http://www.timba.com/tours/maraca"}
{"ArtistLink": "http://www.timba.com/tours/maravilla-de-florida"}
{"ArtistLink": "http://www.timba.com/tours/mart-nez-pedrito"}
{"ArtistLink": "http://www.timba.com/tours/mayimbe-barbaro-fines-y-su-orquesta"}
{"ArtistLink": "http://www.timba.com/tours/maykel-blanco-y-salsa-mayor"}
{"ArtistLink": "http://www.timba.com/tours/mendoza-waldo"}
{"ArtistLink": "http://www.timba.com/tours/mezcla"}
{"ArtistLink": "http://www.timba.com/tours/miguel-enriquez"}
{"ArtistLink": "http://www.timba.com/tours/monika-y-su-maquina"}
{"ArtistLink": "http://www.timba.com/tours/munequitos-de-matanzas"}
{"ArtistLink": "http://www.timba.com/tours/ng-la-banda"}
{"ArtistLink": "http://www.timba.com/tours/noro-y-1ra-clase"}
{"ArtistLink": "http://www.timba.com/tours/orishas"}
{"ArtistLink": "http://www.timba.com/tours/orquesta-aragon"}
{"ArtistLink": "http://www.timba.com/tours/osdalgia"}
{"ArtistLink": "http://www.timba.com/tours/osmani-garcia"}
{"ArtistLink": "http://www.timba.com/tours/calixto-oviedo"}
{"ArtistLink": "http://www.timba.com/tours/pablo-milanes"}
{"ArtistLink": "http://www.timba.com/tours/pachito-alonso-sus-kini-kini"}
{"ArtistLink": "http://www.timba.com/tours/pacific-mambo-orchestra"}
{"ArtistLink": "http://www.timba.com/tours/papucho-manana-club"}
{"ArtistLink": "http://www.timba.com/tours/paulito-fg"}
{"ArtistLink": "http://www.timba.com/tours/pedrito-calvo-la-justicia"}
{"ArtistLink": "http://www.timba.com/tours/pedrito-calvo-jr"}
{"ArtistLink": "http://www.timba.com/tours/pedro-camacho-el-clan"}
{"ArtistLink": "http://www.timba.com/tours/el-pikete"}
{"ArtistLink": "http://www.timba.com/tours/pupy-y-los-que-son-son"}
{"ArtistLink": "http://www.timba.com/tours/rev-oderquis"}
{"ArtistLink": "http://www.timba.com/tours/reve"}
{"ArtistLink": "http://www.timba.com/tours/rivera-mario-mayito"}
{"ArtistLink": "http://www.timba.com/tours/arturo-sandoval"}
{"ArtistLink": "http://www.timba.com/tours/septeto-habanero"}
{"ArtistLink": "http://www.timba.com/tours/septeto-nacional"}
{"ArtistLink": "http://www.timba.com/tours/septeto-santiaguero"}
{"ArtistLink": "http://www.timba.com/tours/sierra-maestra"}
{"ArtistLink": "http://www.timba.com/tours/el-indio"}
{"ArtistLink": "http://www.timba.com/tours/sosa-omar"}
{"ArtistLink": "http://www.timba.com/tours/sur-caribe"}
{"ArtistLink": "http://www.timba.com/tours/www-tiempolibremusic-com"}
{"ArtistLink": "http://www.timba.com/tours/timbalive"}
{"ArtistLink": "http://www.timba.com/tours/timbasa"}
{"ArtistLink": "http://www.timba.com/tours/timbazo"}
{"ArtistLink": "http://www.timba.com/tours/53"}
{"ArtistLink": "http://www.timba.com/tours/tumbao-habana"}
{"ArtistLink": "http://www.timba.com/tours/los-van-van"}
{"ArtistLink": "http://www.timba.com/tours/vocal-sampling"}
{"ArtistLink": "http://www.timba.com/tours/will-campa-la-gran-union"}
{"ArtistLink": "http://www.timba.com/tours/x-alfonso"}
{"ArtistLink": "http://www.timba.com/tours/yarien"}
{"ArtistLink": "http://www.timba.com/tours/yasser-ramos-tumbao-mayombe"}
{"ArtistLink": "http://www.timba.com/tours/yulien"}
{"ArtistLink": "http://www.timba.com/tours/yuly-havana-c"}
{"ArtistLink": "http://www.timba.com/tours/yumuri"}
